# Generated by Django 5.2.14 on 2026-05-15 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_key', models.CharField(max_length=255, unique=True)),
                ('uid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.TextField()),
                ('authors', models.JSONField(blank=True, default=list)),
                ('journal', models.CharField(blank=True, db_index=True, max_length=255)),
                ('publisher', models.CharField(blank=True, db_index=True, max_length=120)),
                ('year', models.CharField(blank=True, db_index=True, max_length=10)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('citations', models.PositiveIntegerField(default=0)),
                ('open_access', models.BooleanField(default=False)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-year', '-citations', 'title'),
            },
        ),
        migrations.CreateModel(
            name='FavoritePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_papers', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='papers.paper')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='UserPaperMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_queries', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('relevance_score', models.FloatField(default=0)),
                ('last_matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to='papers.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_matched_at', '-relevance_score'),
                'unique_together': {('user', 'paper')},
            },
        ),
    ]
