# Generated by Django 5.2.14 on 2026-05-15 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_by', models.CharField(choices=[('year', 'Newest first'), ('cited', 'Most cited'), ('alpha', 'A → Z')], default='year', max_length=20)),
                ('default_result_limit', models.PositiveIntegerField(default=50)),
                ('preferred_publisher', models.CharField(blank=True, max_length=120)),
                ('preferred_journal', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_terms', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('journals_of_interest', models.JSONField(blank=True, default=list)),
                ('extra_queries', models.JSONField(blank=True, default=list)),
                ('arxiv_enabled', models.BooleanField(default=True)),
                ('arxiv_queries', models.JSONField(blank=True, default=list)),
                ('arxiv_categories', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
